// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ivanrwszgvuktmcwfukv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml2YW5yd3N6Z3Z1a3RtY3dmdWt2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIxMzA1MTksImV4cCI6MjA1NzcwNjUxOX0.aW0IlkS91iSqlzNzCLyhEFbv5JxBYTmq4aMfiZbvKpA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);